### ISSUE TITLE
Linking into library on Linux

### ISSUE THREAD

**Issue by MojoForPresident** [premake/premake-core#1338]
Hello,

I hope I am not overlooking something obvious, but I am kind of stuck with this issue right now. Please be aware that I am still learning about C++ in general.

So I am working a project on Windows and created a premake project for it. Basically, I have a static library and a console app in my workspace. Additionally I build the window creation library GLFW from source and link it into my own static library.

Here is my workspace premake5.lua:

```
workspace "MojoEngine"
	architecture "x64"
	startproject "TestApp"
	language "C++"

	configurations { "Debug", "Release" }

	flags {
		"MultiProcessorCompile"
	}

	filter { "configurations:Debug" }
		symbols "On"

	filter { "configurations:Release" }
		symbols "On"

	filter {}


     outputdir = "%{cfg.buildcfg}"

     -- Other projects, here the premake5.lua for GLFW is located
     include "vendor/GLFW"
     project "TestLib"
	kind "StaticLib"

	location "TestLib"
	cppdialect "C++17"
	staticruntime "on"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files {
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs {
		"vendor/GLFW/include"
	}

	filter "system:linux"
		links {
			"dl",
			"X11",
			"pthread",
			"GLAD",
			"GLFW"
		}

		defines {
			"PLATFORM_LINUX"
		}

	filter "system:windows"
		systemversion "latest"
		
		links {
			"GLAD",
			"GLFW",
			"opengl32.lib"
		}

		defines {
			"GLFW_INCLUDE_NONE",
			"PLATFORM_WINDOWS"
		}

   project "TestApp"
	kind "ConsoleApp"

	location "TestApp"
	cppdialect "C++17"
	staticruntime "on"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files {
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs {
		"TestLib/src",
		"vendor/GLFW/include"
	}

	links {
		"GLFW",
		"TestLib"
	}

	filter "system:linux"
		systemversion "latest"

		defines {
			"PLATFORM_LINUX"
		}

	filter "system:windows"
		systemversion "latest"

		defines {
			"GLFW_INCLUDE_NONE",
			"PLATFORM_WINDOWS"
		}
```

I know for a fact that GLFW builds correctly.

Here are my test source files:

TestLib.h:
```
  #if !defined(__WINDOW__)
  #define __WINDOW__

  #include <GLFW/glfw3.h>

  class Window
  {
  public:
      void create();
      void update();
      bool shouldClose();

  private:
      GLFWwindow* window;
  };

  #endif // __WINDOW__
```

TestLib.cpp
```
  #include "TestLib.h"

  void Window::create()
  {
      if (!glfwInit())
	  {
	  	return;
	  }

      window = glfwCreateWindow(600, 600, "Hello World", NULL, NULL);
  }

  void Window::update()
  {
  	glfwPollEvents();
  }

  bool Window::shouldClose()
  {
      return glfwWindowShouldClose(window);
  }
```

Main.cpp:
```
  #include <TestLib.h>

  int main()
  {
  	Window* window = new Window();
  	while(!window->shouldClose())
  	{
  		window->update();
  	}

  	delete window;
  	return 0;
  }
```

Now comes the catch, on Windows it all works perfectly fine, but on Linux I get linker errors for undefined references to all the glfw function (like glfwInit() etc.)

I am kind of lost right now and would appreciate any help.
If this is completely off topic though, please feel free to say so and close this issue (it is the first one I ever opened)

Thanks a lot in advance!

**Comment by MojoForPresident** [comment]
Sorry for the formatting...

**Comment by samsinsane** [comment]
I've fixed up the formatting, for big code blocks like that you need to use three backticks instead of just one. 😄

**Comment by samsinsane** [comment]
I can't see any references to `libdirs`, it's possible that VS treats the `targetdir` as a place to search for dependencies? I otherwise can't explain why VS works at all, try specify `libdirs { "%{cfg.targetdir}" }` for the test app?

**Comment by MojoForPresident** [comment]
@samsinsane Hmm okay so I tried that but it stilll does not work.
Apart from that, I thought that when you link against projects in your workspace premake automatically detects the correct library path.

Here is part of the generated Makefile for my TestApp project and it seems to link the libTestLib.o

```LIBS += ../bin/Debug/TestLib/libTestLib.a
   LDDEPS += ../bin/Debug/TestLib/libTestLib.a```

Just one general question, if I link GLFW into my TestLib, do I have to link against GLFW in TestApp too?

**Comment by samsinsane** [comment]
> I thought that when you link against projects in your workspace premake automatically detects the correct library path.

My apologies, I must have misread your example above, you are correct.

> Just one general question, if I link GLFW into my TestLib, do I have to link against GLFW in TestApp too?

Yes, only Visual Studio does the merging of library files automatically.

**Comment by MojoForPresident** [comment]
Okay thank you for that clarification.
Now my TestApp looks like this:

```	links {
		"GLFW",
		"TestLib"
	}´´´

and Makefile also includes that link. But it still does not work.
So my final question: Should it work now and I am just missing something else? In that case I will close this issue, since I clearly have to figure that out on my own...

**Comment by samsinsane** [comment]
> Should it work now and I am just missing something else?

It should be working, unfortunately I won't have much time this week to look at this properly. The only thing I can think of is that maybe there's a casing problem in your repo?

**Comment by ratzlaff** [comment]
What is your compiler error? (copy and paste that into here)

**Comment by MojoForPresident** [comment]
@samsinsane Than's a lot for helping me though! As this is my first issue it was nice seeing someone helping even though it might just be my own fault... :D

**Comment by MojoForPresident** [comment]
@ratzlaff It is a linker error and in german, but here it is:

```
../bin/Debug/TestLib/libTestLib.a(TestLib.o): In Funktion »Window::create()«:
/home/<path_to_project>/TestLib/src/TestLib.cpp:5: Warnung: undefinierter Verweis auf »glfwInit«
```
and all the other glfw functions called get reported as well.

**Comment by MojoForPresident** [comment]
Basically an undefined reference error.

**Comment by ratzlaff** [comment]
What is the script that creates the GLFW premake project? First thing I would look at is if there is a filter being applied that only adds files to one platform and not another.

**Comment by MojoForPresident** [comment]
Here is my premake5.lua for GLFW:

```
project "GLFW"
	kind "StaticLib"
	language "C"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"include/GLFW/glfw3.h",
		"include/GLFW/glfw3native.h",
		"src/glfw_config.h",
		"src/context.c",
		"src/init.c",
		"src/input.c",
		"src/monitor.c",
		"src/vulkan.c",
		"src/window.c"
	}

	filter "system:linux"
		systemversion "latest"
		staticruntime "On"

		files
		{
			"src/x11_init.c",
			"src/x11_monitor.c",
			"src/x11_window.c",
			"src/xkb_unicode.c",
			"src/posix_time.c",
			"src/posix_thread.c",
			"src/glx_context.c",
			"src/egl_context.c",
			"src/osmesa_context.c",
			"src/linux_joystick.c"
		}

		defines
		{
			"_GLFW_X11"
		}

	filter "system:windows"
		systemversion "latest"
		staticruntime "On"

		files
		{
			"src/win32_init.c",
			"src/win32_joystick.c",
			"src/win32_monitor.c",
			"src/win32_time.c",
			"src/win32_thread.c",
			"src/win32_window.c",
			"src/wgl_context.c",
			"src/egl_context.c",
			"src/osmesa_context.c"
		}

		defines 
		{ 
			"_GLFW_WIN32",
			"_CRT_SECURE_NO_WARNINGS"
		}

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		runtime "Release"
		optimize "on"
```

One weird thing is, if I cut out the TestLib, replace the calls to it in main.cpp by the glfw functions and link directly to GLFW, it works. So GLFW is building and linking correctly and the only difference is that I am basically "forwarding" the calls through TestLib.

**Comment by ratzlaff** [comment]
Does anything change when you put a `filter {}` at the end of your premake5.lua for GLFW?

**Comment by ratzlaff** [comment]
> One weird thing is, if I cut out the TestLib, replace the calls to it in main.cpp by the glfw functions and link directly to GLFW, it works. So GLFW is building and linking correctly and the only difference is that I am basically "forwarding" the calls through TestLib.

So, someone please correct me if I am wrong, but I would have originally said that static libraries do not "link together" to create super-libraries (TestLib) containing everything of one (GLFW in your case) with additional symbols (TestLib sources).

If you go back to your original setup (main, TestLib, GLFW) and link main to both TestLib and GLFW, does it work?

**Comment by MojoForPresident** [comment]
> So, someone please correct me if I am wrong, but I would have originally said that static libraries do not "link together" to create super-libraries (TestLib) containing everything of one (GLFW in your case) with additional symbols (TestLib sources).

True, that is what @samsinsane said before, you have to manually link to all the libraries that are used anywhere in TestLib.
That is what I have done and it did't work. I linked TestApp against TestLib **and** GLFW

The attached .zip is a sample without GLFW that shows my Problem. It has two libraries, the seconde one uses the first one and the application uses the second library.
When I run make I get an undefined reference linker error.

Hope this clarifies my issue, thank you so much for your help!
[LinkTest.zip](https://github.com/premake/premake-core/files/3673851/LinkTest.zip)

**Comment by MojoForPresident** [comment]
> Does anything change when you put a filter {} at the end of your premake5.lua for GLFW?

No, unfortunately not.

**Comment by samsinsane** [comment]
Ah the issue isn't that your app references GFLW and the linker can't find it, it's that the lib references it and the linker can't find it (yet). If you specify `linkgroups "On"` it should resolve the issue, similarly, you can swap the `links` values around. The linker will link backwards, so if you specify A, B, C, it will link C first, and if you have a dependency chain you need to specify them in the correct order - or you can use `linkgroups "On"` and never worry about the order.

**Comment by MojoForPresident** [comment]
Wow thank you so much! This was the problem. I compiles and links now.
This `linkgroups "on"` is pretty handy.

Have a nice day/night @samsinsane  and @ratzlaff, you really helped me out there!
