### ISSUE TITLE
Strange filter setup in Visual Studio 2015 project

### ISSUE THREAD

**Issue by sagamusix** [premake/premake-core#552]
Premake 5 alpha 9 seems to generate rather strange project filters under certain conditions, at least for VS2015 projects. Our directory structure is as follows:
```
build/premake <-- premake scripts here
build/vs2015 <-- VS solution is put here
code-folder1
code-folder2
...
code-folderN
```

So far the solution only included items from all the code folders, so it generated filters named `code-folder1` through `code-folderN`. This is all fine and logical.

New situation: We want to add a file to the project which resides in `build/debug/`.
Now the new filter structure generated in the VS project is as follows:
```
debug
..
     code-folder1
     code-folder2
     ...
     code-folderN
```
As you can see, the two top-level folders are now `debug` and `..`, which does not seem very useful for me. I would expect the top-level folders to stay the same, with the addition of a `build/debug` folder.

**Comment by tvandijck** [comment]
Do you have a simple repro case you can attach to this report? a simple zip file with the project (or a similar stripped down one)... that way we can have a look at this...

**Comment by sagamusix** [comment]
I can try minimizing it, but for now here's the original project:
https://source.openmpt.org/browse/openmpt/trunk/OpenMPT/
Put premake5.exe in `include/premake/` and run `build/regenerate_vs_projects.cmd`.

**Comment by sagamusix** [comment]
I can try minimizing it, but for now here's the original project:
https://source.openmpt.org/browse/openmpt/trunk/OpenMPT/
The following modifications are required to reproduce the problem:
Extract [build.zip](https://github.com/premake/premake-core/files/390952/build.zip) to `build`.
Put premake5.exe in `include/premake/` and run `build/regenerate_vs_projects.cmd`.
The generated problematic project is `build/vs2015/OpenMPT.vcxproj.filters`.

**Comment by tvandijck** [comment]
awesome, thanx... it might not be today, but I'll try to take a look at this.

**Comment by manxorist** [comment]
I am working on the same project as @sagamusix .
I made a minimized test case which mimics our project structure for this.
Run `premake5.exe vs2015`.
[test.zip](https://github.com/premake/premake-core/files/390977/test.zip)

**Comment by tvandijck** [comment]
I'm getting this:
![image](https://cloud.githubusercontent.com/assets/451515/17258547/51ec9dc4-557c-11e6-98e2-dc2b51bffcc9.png)

That seems correct given no 'vpaths' are used, and premake just searching for the highest common root.

**Comment by sagamusix** [comment]
Well, from my understanding the highest common root would be the base directory (i.e. the one that contains `build`, `src` and `src2`), not `build`? At least I can't imagine that having a `..` directory in your project structure can be considered sensible.

**Comment by manxorist** [comment]
I would expect:

```
build/vs/debug/
src/
src2/
```
(common root at `/`)

instead of

```
vs/debug/
../src/
../src2/
```
(common root at `/build/`).

As far as I understand it, if premake is expected to select the highest common root, it's doing something wrong here.

Also, note that it does the correct thing as soon as you remove `../src2/foo2.cpp` from `foo.lua`, which is surprising at best.

**Comment by tvandijck** [comment]
> At least I can't imagine that having a .. directory in your project structure can be considered sensible.

It is this function that decides what the 'vpath' needs to be if nothing is specified.
https://github.com/premake/premake-core/blob/master/src/base/project.lua#L317

Since foo.lua lives in build/premake, what it has calculated for all paths in the project is:
../../src/src
../../src/src2
../vs/debug

All three start with exactly the same "../" so it removes that but leaves the rest intact since those are not common. Which leaves you with the structure you see in the picture I mentioned earlier. Given the implementation that makes perfect sense to me to be honest. right or wrong... it can easily be fixed by explicitly setting the vpath

https://github.com/premake/premake-core/wiki/vpaths

**Comment by tvandijck** [comment]
> Also, note that it does the correct thing as soon as you remove ../src2/foo2.cpp from foo.lua, which is surprising at best.

I agree that that is certainly odd...

**Comment by manxorist** [comment]
> it can easily be fixed by explicitly setting the vpath
> https://github.com/premake/premake-core/wiki/vpaths

I can confirm that setting `vpaths { ["*"] = "../../" }` in the project would solve the problem for us.

However:

>> Also, note that it does the correct thing as soon as you remove ../src2/foo2.cpp from foo.lua, which is surprising at best.

> I agree that that is certainly odd...

It at least does not match your explanation above.
I did not yet did into the lua code itself though.

**Comment by tvandijck** [comment]
Ok, so after some debugging, what premake actually does is this:

the vpaths I get for each file are:
../../src/foo.cpp
../../src2/foo2.cpp
../build/vs/debug/foodebug.cpp

So I get the following tree
* ..
  * ..
    * src
    * src2
  * build
    * vs
      * debug

then we run "tree.trimroot", which seems to have logic to remove single child top nodes, as well as '..' nodes with a single child. The later being the case when src2 is removed from foo.lua..

**Comment by sagamusix** [comment]
I guess in the context of the original bug report this issue could be closed (as @manxorist points out, setting the vpath works as intended for us), but I'm still not sure the current behaviour is optimal. From a purely logical point of view the output might be correct, but from the user's point of view it might make more sense to do the common root elimination based on the full absolute path rather than the relative paths provided in the config files - although I have no idea if this is easily doable in lua, let alone in a cross-platform manner (WinAPI has a function to normalize filenames).

**Comment by tvandijck** [comment]
Agreed, we may want to open a new issue for that, or at least start a discussion on the forum:
https://groups.google.com/forum/#!forum/premake-development

I'll close this one.
